

# This file was *autogenerated* from the file draw.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_0p5 = RealNumber('0.5')
from math import sin, cos, pi
P = graphs.PetersenGraph()
d = {'#FF0000': [_sage_const_0 , _sage_const_5 ], '#FF9900': [_sage_const_1 , _sage_const_6 ], '#FFFF00': [_sage_const_2 , _sage_const_7 ],
     '#00FF00': [_sage_const_3 , _sage_const_8 ], '#0000FF': [_sage_const_4 ,_sage_const_9 ]}
pos_dict = {}
for i in range(_sage_const_5 ):
 x = float(cos(pi/_sage_const_2  + ((_sage_const_2 *pi)/_sage_const_5 )*i))
 y = float(sin(pi/_sage_const_2  + ((_sage_const_2 *pi)/_sage_const_5 )*i))
 pos_dict[i] = [x,y]
for i in range(_sage_const_5 , _sage_const_10 ):
 x = float(_sage_const_0p5 *cos(pi/_sage_const_2  + ((_sage_const_2 *pi)/_sage_const_5 )*i))
 y = float(_sage_const_0p5 *sin(pi/_sage_const_2  + ((_sage_const_2 *pi)/_sage_const_5 )*i))
 pos_dict[i] = [x,y]
pl = P.graphplot(pos=pos_dict, vertex_colors=d)
pl.show()

