

# This file was *autogenerated* from the file graphs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_0 = Integer(0)
n = _sage_const_5 
Gs = list(graphs(n))
print(len(Gs), "non-isomorphic graphs on", n, "vertices")

G = Gs[_sage_const_0 ]
print("Spectrum:", G.spectrum())

