

# This file was *autogenerated* from the file myf.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_1 = Integer(1)
n = _sage_const_5   # change this (safe up to ~8; 9+ explodes)
gen = graphs(n)          # generator of all non-isomorphic graphs on n vertices
count = sum(_sage_const_1  for _ in gen)
count
n = _sage_const_5 
Gs = list(graphs(n))
len(Gs)    # number of non-isomorphic graphs on n vertices

