

# This file was *autogenerated* from the file draw_n_e_graphs_2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_6 = Integer(6)
import os

n = _sage_const_7       # number of vertices
e = _sage_const_6       # number of edges
folder = f"graphs_{n}_{e}edges"

# Create folder if it doesn’t exist
os.makedirs(folder, exist_ok=True)

# Generate all non-isomorphic graphs with n vertices
Gs = list(graphs(n))

# Filter by number of edges
Gs_filtered = [G for G in Gs if G.size() == e]

print(f"Total graphs with {n} vertices and {e} edges: {len(Gs_filtered)}")

for i, G in enumerate(Gs_filtered):
    # --- Save PNG image ---
    P = G.plot()
    img_file = os.path.join(folder, f"graph_{n}_{e}edges_{i}.png")
    P.save(img_file)

    # --- Matrices ---
    A = G.adjacency_matrix()
    L = G.laplacian_matrix()
    D = A.diagonal_matrix()   # degree matrix (actually, wrong: need to fix below)

    # Correct degree matrix
    degrees = G.degree()
    D = matrix.diagonal(degrees)

    Q = D + A  # signless Laplacian

    # --- Save detailed spectral info ---
    txt_file = os.path.join(folder, f"graph_{n}_{e}edges_{i}.txt")
    with open(txt_file, "w") as f:
        f.write(f"Graph {i} with {n} vertices and {e} edges\n")
        f.write(f"Edges: {G.edges()}\n\n")

        f.write("Adjacency Matrix:\n")
        f.write(str(A) + "\n\n")

        f.write("Degree sequence:\n")
        f.write(str(G.degree_sequence()) + "\n\n")

        f.write("Adjacency Spectrum:\n")
        f.write(str(G.spectrum()) + "\n\n")

        f.write("Laplacian Spectrum:\n")
        f.write(str(G.spectrum(laplacian=True)) + "\n\n")

        f.write("Signless Laplacian Spectrum:\n")
        f.write(str(Q.eigenvalues()) + "\n")

    print(f"Saved {img_file} and {txt_file}")


