

# This file was *autogenerated* from the file draw_n_graphs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8)
import os

n = _sage_const_8    # number of vertices
folder = f"graphs_{n}"   # folder name depends on n

# Create the folder if it doesn’t exist
os.makedirs(folder, exist_ok=True)

# Generate all non-isomorphic graphs with n vertices
Gs = list(graphs(n))
print(f"Total non-isomorphic graphs on {n} vertices: {len(Gs)}")

# Draw and save each graph
for i, G in enumerate(Gs):
    P = G.plot()
    filename = os.path.join(folder, f"graph_{n}_{i}.png")
    P.save(filename)
    print(f"Saved {filename}")

